-- Active: 1695737303069@@127.0.0.1@3306@sae_3_02
DROP TABLE IF EXISTS SE_PRODUIRE;

DROP TABLE IF EXISTS SE_LOGER;

DROP TABLE IF EXISTS PARTICIPER;

DROP TABLE IF EXISTS ORGANISE;

DROP TABLE IF EXISTS STYLE_MUSICAL;

DROP TABLE IF EXISTS HEBERGEMENT;

DROP TABLE IF EXISTS CONCERT;

DROP TABLE IF EXISTS BILLET;

DROP TABLE IF EXISTS ARTISTE;

DROP TABLE IF EXISTS ACTIVITE;

DROP TABLE IF EXISTS SPECTATEUR;

DROP TABLE IF EXISTS GROUPE;

DROP TABLE IF EXISTS GENRE_MUSICAL;

DROP TABLE IF EXISTS FESTIVAL;

DROP TABLE IF EXISTS LIEUX;
